add s3 serving documents
pypa/bandersnatch pull request #1015
Opened 2021-09-13 10:25 UTC by LeoQuote

related to: https://github.com/pypa/bandersnatch/issues/552

2021-09-13 10:28 UTC, LeoQuote commented
maybe skip news? 

I just added a very simple instruction, mostly just a link to s3 document and consulting cloud provider....Hope this could be helpful.

I don't have an AWS account either, In fact I was setting up mirror on Tencent cloud, but I believe it is feasible in AWS as well.

2021-09-14 03:32 UTC, cooperlees requested changes
This is great. Lets just get a few fixes and I'll merge away. Appreciate this!

2021-09-14 03:32 UTC, cooperlees commented on docs/storage_options.md
> +I assume you have already set up an AWS account and S3 bucket, and the Bandersnatch sync job has been proceeded.
```suggestion
I assume you have already set up an AWS account and S3 bucket, and the Bandersnatch sync job has successfully ran.
```

2021-09-14 03:32 UTC, cooperlees commented on docs/storage_options.md
> +When you enable the website hosting for a bucket, this bucket can be viewed as static website. Using the s3 domain or your customized domain.
NIT - Markdown wants a \n between all headings - Please do to others.

- I need to add prettier auto formattting to our .md files ...

```suggestion
### Enabling website hosting for the bucket

When you enable the website hosting for a bucket, this bucket can be viewed as static website. Using the s3 domain or your customized domain.
```

2021-09-14 03:32 UTC, cooperlees commented on docs/storage_options.md
> +Please read Amazon documents to get detailed instructions: https://docs.aws.amazon.com/AmazonS3/latest/userguide/EnableWebsiteHosting.html
We could make this links ...
```suggestion
Please read Amazon documents to get [detailed instructions](https://docs.aws.amazon.com/AmazonS3/latest/userguide/EnableWebsiteHosting.html)
```

2021-09-14 03:32 UTC, cooperlees commented on docs/storage_options.md
> +Most cloud provider who provide s3-compatible service will provide this service as well. Please consult to your service assistant to get detailed instructions.
```suggestion
Most cloud provider who provide a s3-compatible service will provide this service as well. Please consult to your service assistant to get detailed instructions.
```

2021-09-14 03:32 UTC, cooperlees commented on docs/storage_options.md
> +Please read Amazon documents to get detailed instructions: https://docs.aws.amazon.com/AmazonS3/latest/userguide/website-hosting-cloudfront-walkthrough.html
```suggestion
Please read Amazon documents to get [detailed instructions](https://docs.aws.amazon.com/AmazonS3/latest/userguide/website-hosting-cloudfront-walkthrough.html)
```

2021-09-14 03:32 UTC, cooperlees commented on docs/storage_options.md
> +To enable SwiftStack support the optional `swift` install must be done:
Thanks! haha

2021-09-14 04:07 UTC, cooperlees approved these changes

2021-09-14 04:07 UTC, merged