Issue #1033 - Fixed requirements file parsing when it contains pip options
pypa/bandersnatch pull request #1231
Opened 2022-10-01 07:31 UTC by mbacicc

Fixed bandersnatch crash when requirements file contains [pip options.](https://pip.pypa.io/en/latest/reference/requirements-file-format/#supported-options)

Test result before the PR:

```
self = <[AttributeError("'Requirement' object has no attribute 'name'") raised in repr()] Requirement object at 0x7f230a96c5e0>
requirement_string = '--extra-index-url https://self-hosted-foo.netname/simple --trusted-host self-hosted-foo.netname'

    def __init__(self, requirement_string: str) -> None:
        try:
            req = REQUIREMENT.parseString(requirement_string)
        except ParseException as e:
>           raise InvalidRequirement(
                f'Parse error at "{ requirement_string[e.loc : e.loc + 8]!r}": {e.msg}'
            )
E           packaging.requirements.InvalidRequirement: Parse error at "'--extra-'": Expected W:(0-9A-Za-z)

venv/lib/python3.8/site-packages/packaging/requirements.py:104: InvalidRequirement
```

2022-10-02 02:54 UTC, cooperlees approved these changes
SGTM - I'll try merge some small fixes here too.

2022-10-02 02:54 UTC, cooperlees commented on src/bandersnatch_filter_plugins/allowlist_name.py
> +        if not package_line or package_line.startswith("#") or package_line.startswith("-"):
```suggestion
        if not package_line or package_line.startswith(("#", "-"))):
```
Pretty sure this works - I only tested in 3.10.6 tho ... Don't change if 3.8 can't handle this.

2022-10-02 02:54 UTC, cooperlees commented on CHANGES.md
> +- Fixed requirements file parsing when it contains pip options
```suggestion
# Unreleased

## Bug Fixes

- Fixed requirements file parsing when it contains pip options `PR #1231`
```

2022-10-02 02:57 UTC, cooperlees requested changes
Bummer - please format the files with black.

2022-10-02 03:01 UTC, cooperlees commented on src/bandersnatch_filter_plugins/allowlist_name.py
> +        if not package_line or package_line.startswith(("#", "-"))):
```suggestion
        if not package_line or package_line.startswith(("#", "-")):
```
Seems editing python via the web is evil / I am useless :P

2022-10-02 03:07 UTC, cooperlees commented on src/bandersnatch/tests/plugins/test_allowlist_name.py
> +--extra-index-url https://self-hosted-foo.netname/simple --trusted-host self-hosted-foo.netname
```suggestion
--extra-index-url https://self-hosted-foo.netname/simple
--trusted-host self-hosted-foo.netname
```

2022-10-02 10:02 UTC, mbacicc commented
Sorry, my fault, didn't configure pre-commits.

Seems everything resolved now.

2022-10-03 05:54 UTC, cooperlees approved these changes

2022-10-03 05:54 UTC, merged