Fixed import of packages from requirement files with UTF-16 encoding
pypa/bandersnatch pull request #1387
Opened 2023-02-26 12:04 UTC by francescocaponio

Solves #1386

2023-02-26 21:00 UTC, ichard26 reviewed
This doesn't seem to do anything? It's just opening the file twice without saving the read contents anywhere.

It's probably better to just loudly error in the logs if the filesystem/OS default encoding doesn't work. Maybe we could be smarter about which one we use, but that's beyond my expertise.

2023-02-26 21:07 UTC, francescocaponio commented
Actually I searched a lot and there is no way to know before opening a file which is the encoding.

The try except block tries to open it first with UTF-8 encoding (the more common), if it fails with UnicodeDecode Exception, it opens it with UTF-16, maybe the UTF-16 open in the except block is unuseful, since it will be later opened again to be read. That could be avoided or used in another try except block, if it would be the case in the future (I would hope not). 

Windows powershell exports the requirements file in UTF-16, while bash does it in UTF-8.

As I was explaining ih the #1386, bandersnatch process is quite unattended, I don't want it to be stuck if a wrong encoded file goes in the requirements folder.

2023-02-26 23:02 UTC, cooperlees requested changes
Thanks for attempting a PR. I commented on the issue and I feel we should just use [charset-normalizer](https://pypi.org/project/charset-normalizer/) and detect the encoding and default to `utf-8` if it fails to detect so we support all encoding that `pip` does with requirements files.

2023-02-27 10:52 UTC, francescocaponio commented
I didn't think about PEP rules and actually never noticed I had some UTF-16 encoded requirements until I provided them to bandersnatch. 
Pip installs them without any problem:
![image](https://user-images.githubusercontent.com/66728654/221544433-4a8bbcce-14c9-42e0-9f20-15c40e1f7e2e.png)
pip uses the function auto_decode to open files: https://github.com/pypa/pip/blob/61e85bf27996a9a73170e353374f13b742ad2058/src/pip/_internal/utils/encoding.py#L20
maybe we can use the same too?

2023-02-27 21:17 UTC, cooperlees commented
This is fine that windows does this and pip supports it. Like add pip like support here to bandersnatch please and that will save us ever having to come back to it. I'm all for adding it, but i think it's worth the little bit of extra effort. Thank for diffing in and working it all out.

2023-02-28 19:38 UTC, francescocaponio commented
Ok, sorry to bother you.
I have the edited version, but I'm unable to pass the pre-commit scripts. Can you help me?
The problem is happening here:
![image](https://user-images.githubusercontent.com/66728654/221960318-e0388a1e-1614-448a-b365-30caf99b840a.png)
black adds a whitespace, and flake8 is unhappy about it:
![image](https://user-images.githubusercontent.com/66728654/221960418-2f793958-57cc-4a70-9808-26b11472effb.png)

Did I do something wrong?

BTW pytest is passing.

2023-02-28 21:12 UTC, cooperlees approved these changes
LGTM - Thanks. This will indeed support all pip supports.

I might look into or open a follow up issues to see if we can remove this copy pasted code and move to a library that will be kept up to date for us. But this is fine for now and does more than only adding UTF-16

2023-02-28 21:12 UTC, cooperlees commented on .flake8
> +ignore = E722, P207, W503, E203
Thanks - Wonder how we never hit this ... Just must have never done it.

2023-02-28 21:12 UTC, cooperlees commented on CHANGES.md
> +- Fixed import of packages from requirement files with UTF-16 encoding `PR #1387`
```suggestion
- Fixed reading requirement files with UTF-16 encoding supporting all encoding pip does `PR #1387`
```
We kind of do more than just UTF-16 now ... But I can fix later if you don't get to it.

2023-02-28 21:41 UTC, merged