Upgrade test dependencies pytest and pytest-asyncio
pypa/bandersnatch pull request #1829
Opened 2024-12-01 23:30 UTC by flyinghyrax

This performs the same version changes as #1656 and #1797 in a single merge request, since the associated issues and fixes appear to be related:

- `pytest` => 8.3.4
- `pytest-asyncio` => 0.24.0

This is a major version increment for pytest and a [0ver](https://0ver.org/) minor version increment for pytest-asyncio.

> [!IMPORTANT]
> In my local development environment I am not able to run the Swift storage plugin tests

2024-12-01 23:52 UTC, flyinghyrax commented
The macOS and Linux test failures appear to show `test_delete.py` using the Swift storage plugin, and the swift http connection failing. That has the smell of the connection pool being created in a different event loop than the one used in `delete_path`. When I've got the time I'll look at getting a Swift container or something set up so I can debug it properly.

2024-12-02 01:00 UTC, cooperlees requested changes
I think we want to use the storage backend loop still ... If I get some time I'll try revert that and see what error we get since I think your key check of 
```
asyncio_default_fixture_loop_scope = function
```
was the big fix we needed as we need lots of event loops with how our tests are written ...

2024-12-02 01:00 UTC, cooperlees commented on src/bandersnatch/delete.py
> +    blob_exists = await loop.run_in_executor(
I bet the backend loop is being patch / mocked or something to make the tests work.

So I bet we don't want to do this change and workout why the backend's loop is failing here ...

2024-12-04 03:11 UTC, cooperlees commented
I can only repro locally on my Mac running latest minio with py3.11 ... on py3.12 it works ... which is interesting ....

2024-12-23 01:30 UTC, flyinghyrax commented
I'm interested in adding `pytest-randomly` to test deps and changing CI to use `-p no:randomly` (so it wouldn't be active in CI) but I will make a separate PR. 🙂

2024-12-23 17:24 UTC, cooperlees approved these changes
Awesome work and many many thanks @flyinghyrax ... This is a huge cleanup with out test suite and will help keeping it cleaner in the future.

Also, love the comment explaining why stuff was done. Can't click merge fast enough!

I will try get a release out over the holiday break finally for 3.12 and start work on making bandersnatch work for 3.13,.

2024-12-23 17:24 UTC, merged

2024-12-24 00:11 UTC, flyinghyrax commented
You're welcome! I'm very happy that I was able to get things working with relatively small changes. 🙂