packages allowlist can deal with inline comments
pypa/bandersnatch pull request #739
Opened 2020-11-19 13:22 UTC by nlaurance-pyie

because working with pip-compile generates requirements files with inline comments like
```
appdirs==1.4.4            # via black
black==20.8b1             # via -r requirements.in
certifi==2020.11.8        # via requests
```

and for now it's convenient to be able to paste it

2020-11-19 15:38 UTC, nlaurance-pyie commented
Packages and releases might be given as requirements.txt files

if requirements_path is missing it is assumed to be root folder

```ini
[plugins]
enabled =
    allowlist_requirements
[allowlist]
requirements_path = /my_folder
requirements =
    requirements.txt
```

2020-11-19 15:52 UTC, nlaurance-pyie commented
addresses issues#736

2020-11-19 17:32 UTC, cooperlees requested changes
Thanks! Nice testing. Please fix typing + black formatting too!

2020-11-19 17:32 UTC, cooperlees commented on docs/filtering_configuration.md
> +if requirements_path is missing it is assumed to be root folder
Root folder as in / or root folder configured in bandersnatch.conf

2020-11-19 17:32 UTC, cooperlees commented on src/bandersnatch_filter_plugins/allowlist_name.py
> +        requirements_path = /where_they_are
Ahh I see here.

2020-11-19 17:32 UTC, cooperlees commented on src/bandersnatch_filter_plugins/allowlist_name.py
> +            requirement_line, *_ = requirement_line.split('#')
```suggestion
            requirement_line, _ = requirement_line.split('#', maxsplits=1)
```
Big fan of max splits

2020-11-19 17:42 UTC, nlaurance-pyie commented on src/bandersnatch_filter_plugins/allowlist_name.py
> +            requirement_line, *_ = requirement_line.split('#')
will do

2020-11-19 17:44 UTC, nlaurance-pyie commented
It doesn't really work yet, that is we need both package and release filtering

2020-11-19 17:52 UTC, nlaurance-pyie commented
`pack, _ = 'package  # comment'.split('#', maxsplit=1)
pack, _ = 'package '.split('#', maxsplit=1)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ValueError: not enough values to unpack (expected 2, got 1)
`

2020-11-19 18:38 UTC, cooperlees commented
I normally just check if we need a split. but happy either way here.

`tox` will run all the lints + type checking locally. You have typing errors. We have pretty strict mypy settings.

2020-11-20 16:06 UTC, cooperlees approved these changes
Thanks for the contribution!
- Like to docker cleanups.
- Tests look pretty comprehensive to me

I’ll aim to release to PyPI this week. Maybe tonight. See how I roll. But I think the Docker Hub image will do for you.

This seems pretty specific - What’s your usage plan here? I’m just interested.

2020-11-20 16:06 UTC, merged